apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes
  labels:
    workflows.argoproj.io/configmap-type: ExecutorPlugin
    workflows.argoproj.io/version: '>= v3.3'
data:
  sidecar.container: |
    name: hermes
    image: ghcr.io/kjagiello/hermes:0.1.0
    imagePullPolicy: IfNotPresent
    command: ['-p', '3030']
    ports:
      - containerPort: 3030
    resources:
      limits:
        cpu: 200m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 32Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
