apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-template-slack-default
data:
  primary: |
    {
      "text": "{{message}}",
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": "{{message}}"
          }
        },
        {
          "type": "section",
          "fields": [
            {
              "type": "mrkdwn",
              "text": "*Application*\n{{app}}"
            },
            {
              "type": "mrkdwn",
              "text": "*Environment*\n{{env}}"
            }
          ]
        },
        {
          "type": "section",
          "fields": [
            {
              "type": "mrkdwn",
              "text": "*Revision*\n<{{revision_url}}|{{revision_sha}}>"
            }
          ]
        },
        {
          "type": "context",
          "elements": [
            {
              "type": "mrkdwn",
              "text": "<{{log_url}}|View pipeline logs>"
            }
          ]
        }
      ]
    }
  secondary: |
    {"text": "{{message}}"}
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-token
stringData:
  token: $SLACK_TOKEN
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: argo
  name: secret-access
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-access-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
roleRef:
  kind: Role
  name: secret-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes
  labels:
    workflows.argoproj.io/configmap-type: ExecutorPlugin
  annotations:
    workflows.argoproj.io/description: |
      This plugin sends a Slack message.
      You must create a secret:
      ```yaml
      apiVersion: v1
      kind: Secret
      metadata:
        name: slack-executor-plugin
      stringData:
        URL: https://hooks.slack.com/services/.../.../...
      ```
      Example:
      ```yaml
      apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      metadata:
        generateName: slack-example-
      spec:
        entrypoint: main
        templates:
          - name: main
            plugin:
              slack:
                text: "{{workflow.name}} finished!"
      ```
    workflows.argoproj.io/version: '>= v3.3'
data:
  sidecar.container: |
    name: hermes
    image: ghcr.io/kjagiello/hermes:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3030
    resources:
      limits:
        cpu: 200m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 32Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
